name: Build Exclave APK

on:
  push:
    branches: [ "dev", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5
      with:
        submodules: 'recursive'

    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'zulu'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # پاک‌سازی فیزیکی و ریشه‌ای تمام کش‌های مخفی کامپایلر و KSP روی دیسک رانر
    - name: Absolute Hard Clean
      run: |
        rm -rf .gradle
        rm -rf build
        rm -rf app/build
        rm -rf plugin/api/build
        rm -rf plugin/naive/build
        rm -rf library/proto-stub/build
        ./gradlew clean

    # فرآیند بیلد تمیز و اجبار به عدم استفاده از کش‌های سیستم‌عاملی قبلی
    - name: Build Debug APK
      run: ./gradlew assembleDebug --no-build-cache --stacktrace -x lint -x test
